### ISSUE TITLE
This repository is violating Hacktoberfest's rules.

### ISSUE THREAD

**Issue by Laphatize** [tarunsinghofficial/HacktoberFest#1179]
Guys once this repository gets flagged DO will revoke this from your progress.
This is entirely unethical and a disgusting way to abuse the free tshirt program.

Please report this repo to https://hacktoberfest.digitalocean.com/report

**Comment by Angelfirenze01** [comment]
In their defense, it wasn't against the rules until this year.  I don't know why they decided to tag it #Hacktoberfest2020, because it is now considered wasteful of time and energy, but -- again -- this wasn't a violation of the terms until this year.

**Comment by tarunsinghofficial** [comment]
h
