### ISSUE TITLE
Concatenation of Consecutive Binary Numbers using C

### ISSUE THREAD

**Issue by Aneesh-07** [tarunsinghofficial/HacktoberFest#2081]
Please assign me this issue under Hacktoberfest 2022

**Comment by Skanda-Prasad** [comment]
Can I work on this issue for Hacktoberfest 2022?

**Comment by croquis** [comment]
Please assign me this issue for Hacktoberfest 2022

**Comment by vivek893** [comment]
Hello sir, can you assign this work to me ?
