### ISSUE TITLE
Circular Linked Lists using c

### ISSUE THREAD

**Issue by Aneesh-07** [tarunsinghofficial/HacktoberFest#2084]
please assign me this issue under hacktoberfest2022

**Comment by aharna** [comment]
hey! I would like to work on this issue

**Comment by tajbaba999** [comment]
Hey! I would Like to work on this issue
In the single linked list, we have only one address In the circular linked list we can have two addresses I would love to contribute In this I have knowledge of the Linked list.
Can you please assign me?

**Comment by AlokPng** [comment]
can you assign this to me

**Comment by Navneet0801** [comment]
Hey @tarunsinghofficial , I would like to contribute in this, So please assign me for contribution!!

**Comment by tomtanner** [comment]
Hello I would like to contribute in this, I have very good knowledge of linked lists, please assign me this issue.

**Comment by suprity04** [comment]
@tarunsinghofficial hey kindly assign me this issue so that I can add an efficient approach for it.

**Comment by Ervin0307** [comment]
Hello @tarunsinghofficial, I would like to work on this issue. Please assign it to me.

**Comment by iTsChEtAn07** [comment]
Hello @tarunsinghofficial , Please assign it to me.

**Comment by AdityaShaw1** [comment]
Hlo can u pls assign me to this issue

**Comment by Mudita-M2** [comment]
please assign this issue to me

**Comment by avnishkt** [comment]
Hello @tarunsinghofficial, I would like to work on this issue. Please assign it to me. under hacktoberfest2022

**Comment by vivek893** [comment]
Hello sir, can you assign this issue to me
