### ISSUE TITLE
Add Stack in C++ 

### ISSUE THREAD

**Issue by cse-vaibhav** [tarunsinghofficial/HacktoberFest#2097]
I want to add a C++ template for Stack Data Structure.

**Comment by cse-vaibhav** [comment]
Assign me to this issue.

**Comment by aksha123-git** [comment]
I would like to contribute in this issues please assign it to me

**Comment by raj-ravan** [comment]
I will be able to contribute in this issues please assign it to me @cse-vaibhav

**Comment by anmol111pal** [comment]
I am new to open source. Please assign me this task.

**Comment by gandhi25samar** [comment]
Please assign me this issue. I want to add C++ template for stack Data structure

**Comment by Harsh0326** [comment]
Hey @tarunsinghofficial  I will be able to contribute in this issues please assign it to me ?

**Comment by Navneet0801** [comment]
Hello @tarunsinghofficial , I would like to contribute in this, So please assign me!!

**Comment by Dharanash** [comment]
I would like to contribute in this issue !

**Comment by mrsingh-rishi** [comment]
I would like to contribute in this issues please assign it to me

**Comment by Ervin0307** [comment]
Hello @cse-vaibhav , I'd like to work on this issue. Please assign it to me.
